# Generated by Django 4.2.4 on 2023-08-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('present_con', models.CharField(blank=True, max_length=200, null=True)),
                ('last_chek_con', models.CharField(blank=True, max_length=200, null=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('last_checkout_at', models.DateTimeField(blank=True, null=True)),
                ('last_return_at', models.DateTimeField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employees')),
            ],
        ),
    ]
