# Generated by Django 4.2.4 on 2023-08-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_gadgets_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='last_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
