# Generated by Django 4.2.4 on 2023-08-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gotgadgetpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgettrackinfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employees')),
                ('gadget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.gadgets')),
            ],
        ),
    ]
