# Generated by Django 4.2.4 on 2023-08-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_gotgadgetpermission_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadgets',
            name='last_checkout_at',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='last_chek_con',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='last_return_at',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='present_con',
        ),
        migrations.AddField(
            model_name='gadgettrackinfo',
            name='checkout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gadgettrackinfo',
            name='last_chek_con',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gadgettrackinfo',
            name='present_con',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gadgettrackinfo',
            name='return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
