# Generated by Django 4.2.4 on 2023-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_gadgets_last_checkout_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadgettrackinfo',
            old_name='present_con',
            new_name='return_con',
        ),
        migrations.AddField(
            model_name='gadgettrackinfo',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
